open module org.subshare.gui {

    requires transitive javafx.controls;
    requires transitive javafx.fxml;

//    requires transitive org.slf4j;

    requires transitive org.subshare.ls.client;
    requires transitive org.subshare.ls.server.cproc;
    requires transitive org.subshare.rest.client;

    exports org.subshare.gui;
    exports org.subshare.gui.backup;
    exports org.subshare.gui.backup.exp;
    exports org.subshare.gui.backup.exp.destination;
    exports org.subshare.gui.backup.exp.first;
    exports org.subshare.gui.backup.imp;
    exports org.subshare.gui.backup.imp.source;
    exports org.subshare.gui.checkout;
    exports org.subshare.gui.concurrent;
    exports org.subshare.gui.control;
    exports org.subshare.gui.createrepo;
    exports org.subshare.gui.createrepo.selectlocaldir;
    exports org.subshare.gui.createrepo.selectowner;
    exports org.subshare.gui.createrepo.selectserver;
    exports org.subshare.gui.error;
    exports org.subshare.gui.filetree;
    exports org.subshare.gui.filetree.repoaware;
    exports org.subshare.gui.histo;
    exports org.subshare.gui.histo.exp;
    exports org.subshare.gui.histo.exp.destination;
    exports org.subshare.gui.histo.exp.option;
    exports org.subshare.gui.invitation.accept;
    exports org.subshare.gui.invitation.accept.checkoutdir;
    exports org.subshare.gui.invitation.accept.source;
    exports org.subshare.gui.invitation.issue;
    exports org.subshare.gui.invitation.issue.destination;
    exports org.subshare.gui.invitation.issue.selectkey;
    exports org.subshare.gui.invitation.issue.selectuser;
    exports org.subshare.gui.localrepo;
    exports org.subshare.gui.localrepo.directory;
    exports org.subshare.gui.localrepo.userrepokeylist;
    exports org.subshare.gui.localrepolist;
    exports org.subshare.gui.ls;
    exports org.subshare.gui.maintree;
    exports org.subshare.gui.pgp.assignownertrust;
    exports org.subshare.gui.pgp.assignownertrust.selectkey;
    exports org.subshare.gui.pgp.assignownertrust.selectownertrust;
    exports org.subshare.gui.pgp.certify;
    exports org.subshare.gui.pgp.createkey;
    exports org.subshare.gui.pgp.createkey.advanced;
    exports org.subshare.gui.pgp.createkey.passphrase;
    exports org.subshare.gui.pgp.createkey.userid;
    exports org.subshare.gui.pgp.createkey.validity;
    exports org.subshare.gui.pgp.creatingkey;
    exports org.subshare.gui.pgp.imp.fromserver;
    exports org.subshare.gui.pgp.keytree;
    exports org.subshare.gui.pgp.privatekeypassphrase;
    exports org.subshare.gui.pgp.selectkey;
    exports org.subshare.gui.resolvecollision;
    exports org.subshare.gui.resolvecollision.collision;
    exports org.subshare.gui.resolvecollision.loading;
    exports org.subshare.gui.scene;
    exports org.subshare.gui.selectuser;
    exports org.subshare.gui.server;
    exports org.subshare.gui.serverlist;
    exports org.subshare.gui.serverrepo;
    exports org.subshare.gui.serverrepo.directory;
    exports org.subshare.gui.severity;
    exports org.subshare.gui.splash;
    exports org.subshare.gui.statusdialog;
    exports org.subshare.gui.user;
    exports org.subshare.gui.userlist;
    exports org.subshare.gui.util;
    exports org.subshare.gui.welcome;
    exports org.subshare.gui.welcome.first;
    exports org.subshare.gui.welcome.identity;
    exports org.subshare.gui.welcome.pgp.privatekeypassphrase;
    exports org.subshare.gui.welcome.pgp.privatekeypassphrase.first;
    exports org.subshare.gui.welcome.server;
    exports org.subshare.gui.wizard;
}